# Generated by Django 4.1.2 on 2023-01-05 18:37

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Request and unique', max_length=255, unique=True, verbose_name='Nosaukums')),
                ('name_lv', models.CharField(help_text='Request and unique', max_length=255, null=True, unique=True, verbose_name='Nosaukums')),
                ('name_en', models.CharField(help_text='Request and unique', max_length=255, null=True, unique=True, verbose_name='Nosaukums')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Kategorijas drošs URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ir aktīvs')),
                ('image', models.ImageField(default='images_category/no-image.png', help_text='Augšupielādējiet produkta attēlu', upload_to='images_category/', verbose_name='Attēls priekš kategorijas')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='majaslapa.category', verbose_name='Līdzīgie produkti')),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorījas',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='nepieciešams', max_length=255, verbose_name='Nosaukums')),
                ('title_lv', models.CharField(help_text='nepieciešams', max_length=255, null=True, verbose_name='Nosaukums')),
                ('title_en', models.CharField(help_text='nepieciešams', max_length=255, null=True, verbose_name='Nosaukums')),
                ('desciption', models.TextField(blank=True, help_text='nav nepieciešams', verbose_name='Apraksts')),
                ('desciption_lv', models.TextField(blank=True, help_text='nav nepieciešams', null=True, verbose_name='Apraksts')),
                ('desciption_en', models.TextField(blank=True, help_text='nav nepieciešams', null=True, verbose_name='Apraksts')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', verbose_name='tīmekļa adreses identifikācija')),
                ('regular_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_lenght': 'Cenai jābūt no 0 līdz 9999,99!'}}, help_text='Maksimums 9999.99', max_digits=6, verbose_name='Parastā cena')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, error_messages={'name': {'max_lenght': 'Cenai jābūt no 0 līdz 9999,99!'}}, help_text='Maksimalais ir 9999.99', max_digits=6, verbose_name='Atlaides cena')),
                ('quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Mainīt produkta redzamību', verbose_name='Produkta redzamība')),
                ('image', models.ImageField(default='images-product/no-image.png', help_text='Augšupielādējiet produkta attēlu', upload_to='images-product/', verbose_name='Attēls')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Izveidots plkst')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Atjaunināts plkst')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='majaslapa.category', verbose_name='Kategorija')),
            ],
            options={
                'verbose_name': 'Prece',
                'verbose_name_plural': 'Preces',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification_value', models.CharField(max_length=255)),
                ('specification_value_lv', models.CharField(max_length=255, null=True)),
                ('specification_value_en', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specification_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.CharField(max_length=255, null=True)),
                ('specifications_lv', models.CharField(max_length=255, null=True)),
                ('specifications_en', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='Augšupielādējiet produkta attēlu', upload_to='images/', verbose_name='Attēls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produkta_attēls', to='majaslapa.product')),
            ],
            options={
                'verbose_name': 'Produkta attēls',
                'verbose_name_plural': 'Produkta attēli',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produkta_specifikacijaa', to='majaslapa.specification'),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1)])),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Apstrāda', 'Apstrāda'), ('Sūta', 'Sūta'), ('Atcelts', 'Atcelts'), ('Pabeigts', 'Pabeigts')], default='Apstrāda', max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majaslapa.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='All_specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specification_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specification_name', to='majaslapa.specification_name')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produkta_specifikacijaa', to='majaslapa.product')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specification_name', to='majaslapa.specification')),
            ],
        ),
    ]
