# Generated by Django 4.1.2 on 2023-01-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0002_product_qwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qwd',
        ),
    ]
