# Generated by Django 4.1.2 on 2023-01-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0003_remove_product_qwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majaslapa.specification'),
        ),
    ]
