# Generated by Django 4.1.2 on 2023-01-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0005_rename_specification_product_specifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specifications',
            new_name='specification',
        ),
    ]
