# Generated by Django 4.1.2 on 2023-01-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0007_remove_product_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='majaslapa.specification'),
        ),
    ]
