# Generated by Django 4.1.2 on 2023-01-05 21:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0010_remove_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='tīmekļa adreses identifikācija'),
        ),
    ]
