# Generated by Django 4.1.2 on 2022-10-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0011_remove_product_category_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Request and unique', max_length=255, null=True, unique=True, verbose_name='Nosaukums'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lv',
            field=models.CharField(help_text='Request and unique', max_length=255, null=True, unique=True, verbose_name='Nosaukums'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_en',
            field=models.CharField(help_text='Obligāti', max_length=255, null=True, unique=True, verbose_name='Produkta nosaukums'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_lv',
            field=models.CharField(help_text='Obligāti', max_length=255, null=True, unique=True, verbose_name='Produkta nosaukums'),
        ),
    ]
