# Generated by Django 4.1.2 on 2023-01-05 21:03

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0012_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='majaslapa.category', verbose_name='Līdzīgie produkti'),
        ),
    ]
