# Generated by Django 4.1.2 on 2023-01-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0014_alter_product_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Obligāti', max_length=255, verbose_name='Nosaukums')),
            ],
            options={
                'verbose_name': 'Produkta specifikācija',
                'verbose_name_plural': 'Produkta specifikācijas',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Produkta specifikācijas vērtība (maksimums 255 vārdi)', max_length=255, verbose_name='Vērtība')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majaslapa.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='majaslapa.productspecification')),
            ],
            options={
                'verbose_name': 'Produkta specifikacijas vērtība',
                'verbose_name_plural': 'Produkta specifikacijas vērtības',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Obligāti', max_length=255, unique=True, verbose_name='Produkta nosaukums')),
            ],
            options={
                'verbose_name': 'Produkta veids',
                'verbose_name_plural': 'Produkta veidi',
            },
        ),
        migrations.DeleteModel(
            name='All_specification',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
        migrations.DeleteModel(
            name='Specification_name',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='Product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='majaslapa.producttype'),
        ),
    ]
