# Generated by Django 4.1.2 on 2023-01-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0015_productspecification_productspecificationvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='name_en',
            field=models.CharField(help_text='Obligāti', max_length=255, null=True, verbose_name='Nosaukums'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='name_lv',
            field=models.CharField(help_text='Obligāti', max_length=255, null=True, verbose_name='Nosaukums'),
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='value_en',
            field=models.CharField(help_text='Produkta specifikācijas vērtība (maksimums 255 vārdi)', max_length=255, null=True, verbose_name='Vērtība'),
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='value_lv',
            field=models.CharField(help_text='Produkta specifikācijas vērtība (maksimums 255 vārdi)', max_length=255, null=True, verbose_name='Vērtība'),
        ),
    ]
