# Generated by Django 4.1.2 on 2022-11-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0023_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='prduct',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
