# Generated by Django 4.1.2 on 2022-11-11 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('majaslapa', '0026_alter_product_image_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='reference description', max_length=255, verbose_name='reference description')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('details', models.CharField(help_text='payment details', max_length=255, verbose_name='details')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='P', max_length=1, verbose_name='status')),
                ('redirect_after_success', models.CharField(editable=False, max_length=255)),
                ('redirect_on_failure', models.CharField(editable=False, max_length=255)),
                ('user', models.ForeignKey(blank=True, default=None, help_text='user who started transaction', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'transaction',
                'ordering': ['-last_modified'],
            },
        ),
    ]
