# Generated by Django 4.1.2 on 2022-11-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0027_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'name': {'max_lenght': 'Cenai jābūt no 0 līdz 9999,99!'}}, help_text='Maksimalais ir 9999.99', max_digits=6, verbose_name='Atlaides cena'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
