# Generated by Django 4.1.2 on 2022-11-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0030_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
    ]
