# Generated by Django 4.1.2 on 2022-11-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0031_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Produkta attēls', 'verbose_name_plural': 'Produkta attēli'},
        ),
    ]
