# Generated by Django 4.1.2 on 2022-11-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0033_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Apstrāda', 'Apstrāda'), ('Sūta', 'Sūta'), ('Atcelts', 'Atcelts'), ('Pabeigts', 'Pabeigts')], default='Apstrāda', max_length=150),
        ),
    ]
