# Generated by Django 4.1.2 on 2022-11-21 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0034_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images_category/no-image.png', help_text='Augšupielādējiet produkta attēlu', upload_to='images_category/', verbose_name='Attēls priekš kategorijas'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images-product/no-image.png', help_text='Augšupielādējiet produkta attēlu', upload_to='images-product/', verbose_name='Attēls'),
        ),
    ]
