# Generated by Django 4.1.2 on 2022-12-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0038_alter_contact_details_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='details',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
