# Generated by Django 4.1.2 on 2022-12-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0039_remove_contact_details_remove_contact_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
