# Generated by Django 4.1.2 on 2022-12-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0041_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_feature',
        ),
    ]
