# Generated by Django 4.1.2 on 2022-12-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0044_alter_productcustomfield_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.DeleteModel(
            name='ProductSpecificationValue',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
