# Generated by Django 4.1.2 on 2022-12-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0045_remove_productspecificationvalue_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=255)),
                ('specification_value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produkta_specifikacija', to='majaslapa.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductCustomField',
        ),
    ]
