# Generated by Django 4.1.2 on 2022-12-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0046_specification_delete_productcustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='specification_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='specification_lv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
