# Generated by Django 4.1.2 on 2022-12-07 15:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0048_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', verbose_name='tīmekļa adreses identifikācija'),
        ),
    ]
