# Generated by Django 4.1.2 on 2022-12-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0049_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='specification_value_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='specification_value_lv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
