# Generated by Django 4.1.2 on 2022-12-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0051_specification_name_alter_specification_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='specification',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='specification',
            name='specification_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='specification_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Specification_name',
        ),
    ]
