# Generated by Django 4.1.2 on 2022-12-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0052_alter_specification_specification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='specification',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Specification_name', to='majaslapa.specification_name'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='specification_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specification_name', to='majaslapa.specification_name'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='specification_lv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specification_name', to='majaslapa.specification_name'),
        ),
    ]
