# Generated by Django 4.1.2 on 2022-12-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0053_specification_name_alter_specification_specification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='specification_en',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='specification_lv',
        ),
    ]
