# Generated by Django 4.1.2 on 2022-12-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0054_remove_specification_specification_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produkta_specifikacijaa', to='majaslapa.product'),
        ),
    ]
