# Generated by Django 4.1.2 on 2022-12-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0058_remove_specification_name_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification_name',
            name='specification_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specification_name',
            name='specification_lv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
